code --install-extension aaron-bond.better-comments
code --install-extension alexandersage.angular1-code-snippets
code --install-extension Angular.ng-template
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension drKnoxy.eslint-disable-snippets
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension felipe-mendes.slack-theme
code --install-extension ghmcadams.lintlens
code --install-extension GitHub.vscode-pull-request-github
code --install-extension Gruntfuggly.todo-tree
code --install-extension hbenl.vscode-test-explorer
code --install-extension humao.rest-client
code --install-extension ivory-lab.jenkinsfile-support
code --install-extension JakeWilson.vscode-cdnjs
code --install-extension jebbs.plantuml
code --install-extension johnpapa.Angular2
code --install-extension johnpapa.vscode-peacock
code --install-extension johnpapa.winteriscoming
code --install-extension kisstkondoros.vscode-codemetrics
code --install-extension Luxcium.pop-n-lock-theme-vscode
code --install-extension ms-azure-devops.azure-pipelines
code --install-extension msazurermtools.azurerm-vscode-tools
code --install-extension ms-azuretools.vscode-apimanagement
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-azuretools.vscode-cosmosdb
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-mssql.mssql
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-ssh-explorer
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.azurecli
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.vscode-node-azure-pack
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension netcorext.uuid-generator
code --install-extension nrwl.angular-console
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension rokoroku.vscode-theme-darcula
code --install-extension rtbenfield.vscode-jest-test-adapter
code --install-extension ryu1kn.partial-diff
code --install-extension shakram02.bash-beautify
code --install-extension shinnn.stylelint
code --install-extension taniarascia.new-moon-vscode
code --install-extension techer.open-in-browser
code --install-extension thenikso.github-plus-theme
code --install-extension ue.alphabetical-sorter
code --install-extension vsciot-vscode.azure-iot-toolkit
code --install-extension wayou.vscode-todo-highlight
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
